/*
 * MetaSV for MVC API Spec
 *
 * API definition for MetaSV provided apis
 *
 * API version: 3.0.3
 * Contact: heqiming@metasv.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metasv

import (
	"encoding/json"
)

// ContractNftAuctionUtxo Contract nft auction Utxo belongs to the specified address
type ContractNftAuctionUtxo struct {
	// Address string of this utxo
	Address *string `json:"address,omitempty"`
	// Txid for this utxo.
	Txid *string `json:"txid,omitempty"`
	// Output index for the Utxo.
	TxIndex *int32 `json:"txIndex,omitempty"`
	// bidMvcPrice
	BidMvcPrice *int64 `json:"bidMvcPrice,omitempty"`
	// bidTimestamp
	BidTimestamp *int64 `json:"bidTimestamp,omitempty"`
	// bidderAddressPkh
	BidderAddressPkh *string `json:"bidderAddressPkh,omitempty"`
	// Codehash of this utxo.
	CodeHash *string `json:"codeHash,omitempty"`
	// Genesis of this utxo.
	Genesis *string `json:"genesis,omitempty"`
	// endTimestamp
	EndTimestamp *int64 `json:"endTimestamp,omitempty"`
	// feeAddressPkh
	FeeAddressPkh *string `json:"feeAddressPkh,omitempty"`
	// feeAmount
	FeeAmount *int64 `json:"feeAmount,omitempty"`
	// feeRate
	FeeRate *int32 `json:"feeRate,omitempty"`
	// The height of this utxo, -1 for unconfirmed utxo.
	Height *int64 `json:"height,omitempty"`
	// nftCodeHash
	NftCodeHash *string `json:"nftCodeHash,omitempty"`
	// nftId of the auctioning fnt
	NftId *string `json:"nftId,omitempty"`
	// senderAddressPkh
	SenderAddressPkh *string `json:"senderAddressPkh,omitempty"`
	// SensibleId of the utxo
	SensibleId *string `json:"sensibleId,omitempty"`
	// startMvcPrice
	StartMvcPrice *int64 `json:"startMvcPrice,omitempty"`
	// Mvc value of the utxo(Irrelavant to token value)
	Satoshi *int64 `json:"satoshi,omitempty"`
	// Mvc value of the utxo(In string format)
	SatoshiString *string `json:"satoshiString,omitempty"`
	// The hash160 of the script(p2ch address)
	ContractAddress *string `json:"contractAddress,omitempty"`
	// this the nft send to this contract address
	IsReady *bool `json:"isReady,omitempty"`
	// Flag used for paging
	Flag *string `json:"flag,omitempty"`
}

// NewContractNftAuctionUtxo instantiates a new ContractNftAuctionUtxo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContractNftAuctionUtxo() *ContractNftAuctionUtxo {
	this := ContractNftAuctionUtxo{}
	return &this
}

// NewContractNftAuctionUtxoWithDefaults instantiates a new ContractNftAuctionUtxo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContractNftAuctionUtxoWithDefaults() *ContractNftAuctionUtxo {
	this := ContractNftAuctionUtxo{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ContractNftAuctionUtxo) SetAddress(v string) {
	o.Address = &v
}

// GetTxid returns the Txid field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetTxid() string {
	if o == nil || o.Txid == nil {
		var ret string
		return ret
	}
	return *o.Txid
}

// GetTxidOk returns a tuple with the Txid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetTxidOk() (*string, bool) {
	if o == nil || o.Txid == nil {
		return nil, false
	}
	return o.Txid, true
}

// HasTxid returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasTxid() bool {
	if o != nil && o.Txid != nil {
		return true
	}

	return false
}

// SetTxid gets a reference to the given string and assigns it to the Txid field.
func (o *ContractNftAuctionUtxo) SetTxid(v string) {
	o.Txid = &v
}

// GetTxIndex returns the TxIndex field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetTxIndex() int32 {
	if o == nil || o.TxIndex == nil {
		var ret int32
		return ret
	}
	return *o.TxIndex
}

// GetTxIndexOk returns a tuple with the TxIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetTxIndexOk() (*int32, bool) {
	if o == nil || o.TxIndex == nil {
		return nil, false
	}
	return o.TxIndex, true
}

// HasTxIndex returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasTxIndex() bool {
	if o != nil && o.TxIndex != nil {
		return true
	}

	return false
}

// SetTxIndex gets a reference to the given int32 and assigns it to the TxIndex field.
func (o *ContractNftAuctionUtxo) SetTxIndex(v int32) {
	o.TxIndex = &v
}

// GetBidMvcPrice returns the BidMvcPrice field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetBidMvcPrice() int64 {
	if o == nil || o.BidMvcPrice == nil {
		var ret int64
		return ret
	}
	return *o.BidMvcPrice
}

// GetBidMvcPriceOk returns a tuple with the BidMvcPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetBidMvcPriceOk() (*int64, bool) {
	if o == nil || o.BidMvcPrice == nil {
		return nil, false
	}
	return o.BidMvcPrice, true
}

// HasBidMvcPrice returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasBidMvcPrice() bool {
	if o != nil && o.BidMvcPrice != nil {
		return true
	}

	return false
}

// SetBidMvcPrice gets a reference to the given int64 and assigns it to the BidMvcPrice field.
func (o *ContractNftAuctionUtxo) SetBidMvcPrice(v int64) {
	o.BidMvcPrice = &v
}

// GetBidTimestamp returns the BidTimestamp field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetBidTimestamp() int64 {
	if o == nil || o.BidTimestamp == nil {
		var ret int64
		return ret
	}
	return *o.BidTimestamp
}

// GetBidTimestampOk returns a tuple with the BidTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetBidTimestampOk() (*int64, bool) {
	if o == nil || o.BidTimestamp == nil {
		return nil, false
	}
	return o.BidTimestamp, true
}

// HasBidTimestamp returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasBidTimestamp() bool {
	if o != nil && o.BidTimestamp != nil {
		return true
	}

	return false
}

// SetBidTimestamp gets a reference to the given int64 and assigns it to the BidTimestamp field.
func (o *ContractNftAuctionUtxo) SetBidTimestamp(v int64) {
	o.BidTimestamp = &v
}

// GetBidderAddressPkh returns the BidderAddressPkh field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetBidderAddressPkh() string {
	if o == nil || o.BidderAddressPkh == nil {
		var ret string
		return ret
	}
	return *o.BidderAddressPkh
}

// GetBidderAddressPkhOk returns a tuple with the BidderAddressPkh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetBidderAddressPkhOk() (*string, bool) {
	if o == nil || o.BidderAddressPkh == nil {
		return nil, false
	}
	return o.BidderAddressPkh, true
}

// HasBidderAddressPkh returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasBidderAddressPkh() bool {
	if o != nil && o.BidderAddressPkh != nil {
		return true
	}

	return false
}

// SetBidderAddressPkh gets a reference to the given string and assigns it to the BidderAddressPkh field.
func (o *ContractNftAuctionUtxo) SetBidderAddressPkh(v string) {
	o.BidderAddressPkh = &v
}

// GetCodeHash returns the CodeHash field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetCodeHash() string {
	if o == nil || o.CodeHash == nil {
		var ret string
		return ret
	}
	return *o.CodeHash
}

// GetCodeHashOk returns a tuple with the CodeHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetCodeHashOk() (*string, bool) {
	if o == nil || o.CodeHash == nil {
		return nil, false
	}
	return o.CodeHash, true
}

// HasCodeHash returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasCodeHash() bool {
	if o != nil && o.CodeHash != nil {
		return true
	}

	return false
}

// SetCodeHash gets a reference to the given string and assigns it to the CodeHash field.
func (o *ContractNftAuctionUtxo) SetCodeHash(v string) {
	o.CodeHash = &v
}

// GetGenesis returns the Genesis field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetGenesis() string {
	if o == nil || o.Genesis == nil {
		var ret string
		return ret
	}
	return *o.Genesis
}

// GetGenesisOk returns a tuple with the Genesis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetGenesisOk() (*string, bool) {
	if o == nil || o.Genesis == nil {
		return nil, false
	}
	return o.Genesis, true
}

// HasGenesis returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasGenesis() bool {
	if o != nil && o.Genesis != nil {
		return true
	}

	return false
}

// SetGenesis gets a reference to the given string and assigns it to the Genesis field.
func (o *ContractNftAuctionUtxo) SetGenesis(v string) {
	o.Genesis = &v
}

// GetEndTimestamp returns the EndTimestamp field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetEndTimestamp() int64 {
	if o == nil || o.EndTimestamp == nil {
		var ret int64
		return ret
	}
	return *o.EndTimestamp
}

// GetEndTimestampOk returns a tuple with the EndTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetEndTimestampOk() (*int64, bool) {
	if o == nil || o.EndTimestamp == nil {
		return nil, false
	}
	return o.EndTimestamp, true
}

// HasEndTimestamp returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasEndTimestamp() bool {
	if o != nil && o.EndTimestamp != nil {
		return true
	}

	return false
}

// SetEndTimestamp gets a reference to the given int64 and assigns it to the EndTimestamp field.
func (o *ContractNftAuctionUtxo) SetEndTimestamp(v int64) {
	o.EndTimestamp = &v
}

// GetFeeAddressPkh returns the FeeAddressPkh field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetFeeAddressPkh() string {
	if o == nil || o.FeeAddressPkh == nil {
		var ret string
		return ret
	}
	return *o.FeeAddressPkh
}

// GetFeeAddressPkhOk returns a tuple with the FeeAddressPkh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetFeeAddressPkhOk() (*string, bool) {
	if o == nil || o.FeeAddressPkh == nil {
		return nil, false
	}
	return o.FeeAddressPkh, true
}

// HasFeeAddressPkh returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasFeeAddressPkh() bool {
	if o != nil && o.FeeAddressPkh != nil {
		return true
	}

	return false
}

// SetFeeAddressPkh gets a reference to the given string and assigns it to the FeeAddressPkh field.
func (o *ContractNftAuctionUtxo) SetFeeAddressPkh(v string) {
	o.FeeAddressPkh = &v
}

// GetFeeAmount returns the FeeAmount field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetFeeAmount() int64 {
	if o == nil || o.FeeAmount == nil {
		var ret int64
		return ret
	}
	return *o.FeeAmount
}

// GetFeeAmountOk returns a tuple with the FeeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetFeeAmountOk() (*int64, bool) {
	if o == nil || o.FeeAmount == nil {
		return nil, false
	}
	return o.FeeAmount, true
}

// HasFeeAmount returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasFeeAmount() bool {
	if o != nil && o.FeeAmount != nil {
		return true
	}

	return false
}

// SetFeeAmount gets a reference to the given int64 and assigns it to the FeeAmount field.
func (o *ContractNftAuctionUtxo) SetFeeAmount(v int64) {
	o.FeeAmount = &v
}

// GetFeeRate returns the FeeRate field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetFeeRate() int32 {
	if o == nil || o.FeeRate == nil {
		var ret int32
		return ret
	}
	return *o.FeeRate
}

// GetFeeRateOk returns a tuple with the FeeRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetFeeRateOk() (*int32, bool) {
	if o == nil || o.FeeRate == nil {
		return nil, false
	}
	return o.FeeRate, true
}

// HasFeeRate returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasFeeRate() bool {
	if o != nil && o.FeeRate != nil {
		return true
	}

	return false
}

// SetFeeRate gets a reference to the given int32 and assigns it to the FeeRate field.
func (o *ContractNftAuctionUtxo) SetFeeRate(v int32) {
	o.FeeRate = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetHeight() int64 {
	if o == nil || o.Height == nil {
		var ret int64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetHeightOk() (*int64, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int64 and assigns it to the Height field.
func (o *ContractNftAuctionUtxo) SetHeight(v int64) {
	o.Height = &v
}

// GetNftCodeHash returns the NftCodeHash field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetNftCodeHash() string {
	if o == nil || o.NftCodeHash == nil {
		var ret string
		return ret
	}
	return *o.NftCodeHash
}

// GetNftCodeHashOk returns a tuple with the NftCodeHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetNftCodeHashOk() (*string, bool) {
	if o == nil || o.NftCodeHash == nil {
		return nil, false
	}
	return o.NftCodeHash, true
}

// HasNftCodeHash returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasNftCodeHash() bool {
	if o != nil && o.NftCodeHash != nil {
		return true
	}

	return false
}

// SetNftCodeHash gets a reference to the given string and assigns it to the NftCodeHash field.
func (o *ContractNftAuctionUtxo) SetNftCodeHash(v string) {
	o.NftCodeHash = &v
}

// GetNftId returns the NftId field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetNftId() string {
	if o == nil || o.NftId == nil {
		var ret string
		return ret
	}
	return *o.NftId
}

// GetNftIdOk returns a tuple with the NftId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetNftIdOk() (*string, bool) {
	if o == nil || o.NftId == nil {
		return nil, false
	}
	return o.NftId, true
}

// HasNftId returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasNftId() bool {
	if o != nil && o.NftId != nil {
		return true
	}

	return false
}

// SetNftId gets a reference to the given string and assigns it to the NftId field.
func (o *ContractNftAuctionUtxo) SetNftId(v string) {
	o.NftId = &v
}

// GetSenderAddressPkh returns the SenderAddressPkh field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetSenderAddressPkh() string {
	if o == nil || o.SenderAddressPkh == nil {
		var ret string
		return ret
	}
	return *o.SenderAddressPkh
}

// GetSenderAddressPkhOk returns a tuple with the SenderAddressPkh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetSenderAddressPkhOk() (*string, bool) {
	if o == nil || o.SenderAddressPkh == nil {
		return nil, false
	}
	return o.SenderAddressPkh, true
}

// HasSenderAddressPkh returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasSenderAddressPkh() bool {
	if o != nil && o.SenderAddressPkh != nil {
		return true
	}

	return false
}

// SetSenderAddressPkh gets a reference to the given string and assigns it to the SenderAddressPkh field.
func (o *ContractNftAuctionUtxo) SetSenderAddressPkh(v string) {
	o.SenderAddressPkh = &v
}

// GetSensibleId returns the SensibleId field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetSensibleId() string {
	if o == nil || o.SensibleId == nil {
		var ret string
		return ret
	}
	return *o.SensibleId
}

// GetSensibleIdOk returns a tuple with the SensibleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetSensibleIdOk() (*string, bool) {
	if o == nil || o.SensibleId == nil {
		return nil, false
	}
	return o.SensibleId, true
}

// HasSensibleId returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasSensibleId() bool {
	if o != nil && o.SensibleId != nil {
		return true
	}

	return false
}

// SetSensibleId gets a reference to the given string and assigns it to the SensibleId field.
func (o *ContractNftAuctionUtxo) SetSensibleId(v string) {
	o.SensibleId = &v
}

// GetStartMvcPrice returns the StartMvcPrice field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetStartMvcPrice() int64 {
	if o == nil || o.StartMvcPrice == nil {
		var ret int64
		return ret
	}
	return *o.StartMvcPrice
}

// GetStartMvcPriceOk returns a tuple with the StartMvcPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetStartMvcPriceOk() (*int64, bool) {
	if o == nil || o.StartMvcPrice == nil {
		return nil, false
	}
	return o.StartMvcPrice, true
}

// HasStartMvcPrice returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasStartMvcPrice() bool {
	if o != nil && o.StartMvcPrice != nil {
		return true
	}

	return false
}

// SetStartMvcPrice gets a reference to the given int64 and assigns it to the StartMvcPrice field.
func (o *ContractNftAuctionUtxo) SetStartMvcPrice(v int64) {
	o.StartMvcPrice = &v
}

// GetSatoshi returns the Satoshi field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetSatoshi() int64 {
	if o == nil || o.Satoshi == nil {
		var ret int64
		return ret
	}
	return *o.Satoshi
}

// GetSatoshiOk returns a tuple with the Satoshi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetSatoshiOk() (*int64, bool) {
	if o == nil || o.Satoshi == nil {
		return nil, false
	}
	return o.Satoshi, true
}

// HasSatoshi returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasSatoshi() bool {
	if o != nil && o.Satoshi != nil {
		return true
	}

	return false
}

// SetSatoshi gets a reference to the given int64 and assigns it to the Satoshi field.
func (o *ContractNftAuctionUtxo) SetSatoshi(v int64) {
	o.Satoshi = &v
}

// GetSatoshiString returns the SatoshiString field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetSatoshiString() string {
	if o == nil || o.SatoshiString == nil {
		var ret string
		return ret
	}
	return *o.SatoshiString
}

// GetSatoshiStringOk returns a tuple with the SatoshiString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetSatoshiStringOk() (*string, bool) {
	if o == nil || o.SatoshiString == nil {
		return nil, false
	}
	return o.SatoshiString, true
}

// HasSatoshiString returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasSatoshiString() bool {
	if o != nil && o.SatoshiString != nil {
		return true
	}

	return false
}

// SetSatoshiString gets a reference to the given string and assigns it to the SatoshiString field.
func (o *ContractNftAuctionUtxo) SetSatoshiString(v string) {
	o.SatoshiString = &v
}

// GetContractAddress returns the ContractAddress field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetContractAddress() string {
	if o == nil || o.ContractAddress == nil {
		var ret string
		return ret
	}
	return *o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetContractAddressOk() (*string, bool) {
	if o == nil || o.ContractAddress == nil {
		return nil, false
	}
	return o.ContractAddress, true
}

// HasContractAddress returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasContractAddress() bool {
	if o != nil && o.ContractAddress != nil {
		return true
	}

	return false
}

// SetContractAddress gets a reference to the given string and assigns it to the ContractAddress field.
func (o *ContractNftAuctionUtxo) SetContractAddress(v string) {
	o.ContractAddress = &v
}

// GetIsReady returns the IsReady field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetIsReady() bool {
	if o == nil || o.IsReady == nil {
		var ret bool
		return ret
	}
	return *o.IsReady
}

// GetIsReadyOk returns a tuple with the IsReady field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetIsReadyOk() (*bool, bool) {
	if o == nil || o.IsReady == nil {
		return nil, false
	}
	return o.IsReady, true
}

// HasIsReady returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasIsReady() bool {
	if o != nil && o.IsReady != nil {
		return true
	}

	return false
}

// SetIsReady gets a reference to the given bool and assigns it to the IsReady field.
func (o *ContractNftAuctionUtxo) SetIsReady(v bool) {
	o.IsReady = &v
}

// GetFlag returns the Flag field value if set, zero value otherwise.
func (o *ContractNftAuctionUtxo) GetFlag() string {
	if o == nil || o.Flag == nil {
		var ret string
		return ret
	}
	return *o.Flag
}

// GetFlagOk returns a tuple with the Flag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractNftAuctionUtxo) GetFlagOk() (*string, bool) {
	if o == nil || o.Flag == nil {
		return nil, false
	}
	return o.Flag, true
}

// HasFlag returns a boolean if a field has been set.
func (o *ContractNftAuctionUtxo) HasFlag() bool {
	if o != nil && o.Flag != nil {
		return true
	}

	return false
}

// SetFlag gets a reference to the given string and assigns it to the Flag field.
func (o *ContractNftAuctionUtxo) SetFlag(v string) {
	o.Flag = &v
}

func (o ContractNftAuctionUtxo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Txid != nil {
		toSerialize["txid"] = o.Txid
	}
	if o.TxIndex != nil {
		toSerialize["txIndex"] = o.TxIndex
	}
	if o.BidMvcPrice != nil {
		toSerialize["bidMvcPrice"] = o.BidMvcPrice
	}
	if o.BidTimestamp != nil {
		toSerialize["bidTimestamp"] = o.BidTimestamp
	}
	if o.BidderAddressPkh != nil {
		toSerialize["bidderAddressPkh"] = o.BidderAddressPkh
	}
	if o.CodeHash != nil {
		toSerialize["codeHash"] = o.CodeHash
	}
	if o.Genesis != nil {
		toSerialize["genesis"] = o.Genesis
	}
	if o.EndTimestamp != nil {
		toSerialize["endTimestamp"] = o.EndTimestamp
	}
	if o.FeeAddressPkh != nil {
		toSerialize["feeAddressPkh"] = o.FeeAddressPkh
	}
	if o.FeeAmount != nil {
		toSerialize["feeAmount"] = o.FeeAmount
	}
	if o.FeeRate != nil {
		toSerialize["feeRate"] = o.FeeRate
	}
	if o.Height != nil {
		toSerialize["height"] = o.Height
	}
	if o.NftCodeHash != nil {
		toSerialize["nftCodeHash"] = o.NftCodeHash
	}
	if o.NftId != nil {
		toSerialize["nftId"] = o.NftId
	}
	if o.SenderAddressPkh != nil {
		toSerialize["senderAddressPkh"] = o.SenderAddressPkh
	}
	if o.SensibleId != nil {
		toSerialize["sensibleId"] = o.SensibleId
	}
	if o.StartMvcPrice != nil {
		toSerialize["startMvcPrice"] = o.StartMvcPrice
	}
	if o.Satoshi != nil {
		toSerialize["satoshi"] = o.Satoshi
	}
	if o.SatoshiString != nil {
		toSerialize["satoshiString"] = o.SatoshiString
	}
	if o.ContractAddress != nil {
		toSerialize["contractAddress"] = o.ContractAddress
	}
	if o.IsReady != nil {
		toSerialize["isReady"] = o.IsReady
	}
	if o.Flag != nil {
		toSerialize["flag"] = o.Flag
	}
	return json.Marshal(toSerialize)
}

type NullableContractNftAuctionUtxo struct {
	value *ContractNftAuctionUtxo
	isSet bool
}

func (v NullableContractNftAuctionUtxo) Get() *ContractNftAuctionUtxo {
	return v.value
}

func (v *NullableContractNftAuctionUtxo) Set(val *ContractNftAuctionUtxo) {
	v.value = val
	v.isSet = true
}

func (v NullableContractNftAuctionUtxo) IsSet() bool {
	return v.isSet
}

func (v *NullableContractNftAuctionUtxo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContractNftAuctionUtxo(val *ContractNftAuctionUtxo) *NullableContractNftAuctionUtxo {
	return &NullableContractNftAuctionUtxo{value: val, isSet: true}
}

func (v NullableContractNftAuctionUtxo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContractNftAuctionUtxo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
