/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * API version: 3.0.8
 * Contact: heqiming@metasv.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metasv

import (
	"encoding/json"
)

// AddressTx Transaction history of the address.
type AddressTx struct {
	// Paging flag
	Flag *string `json:"flag,omitempty"`
	// The address of the record
	Address *string `json:"address,omitempty"`
	// timestamp of the tx
	Time *int64 `json:"time,omitempty"`
	// Block Height of the tx, -1 if not confirmed
	Height *int64 `json:"height,omitempty"`
	// total income of the address from this tx
	Income *int64 `json:"income,omitempty"`
	// total outcome of the address from this tx
	Outcome *int64 `json:"outcome,omitempty"`
	// txid of this record
	Txid *string `json:"txid,omitempty"`
}

// NewAddressTx instantiates a new AddressTx object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressTx() *AddressTx {
	this := AddressTx{}
	return &this
}

// NewAddressTxWithDefaults instantiates a new AddressTx object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressTxWithDefaults() *AddressTx {
	this := AddressTx{}
	return &this
}

// GetFlag returns the Flag field value if set, zero value otherwise.
func (o *AddressTx) GetFlag() string {
	if o == nil || o.Flag == nil {
		var ret string
		return ret
	}
	return *o.Flag
}

// GetFlagOk returns a tuple with the Flag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressTx) GetFlagOk() (*string, bool) {
	if o == nil || o.Flag == nil {
		return nil, false
	}
	return o.Flag, true
}

// HasFlag returns a boolean if a field has been set.
func (o *AddressTx) HasFlag() bool {
	if o != nil && o.Flag != nil {
		return true
	}

	return false
}

// SetFlag gets a reference to the given string and assigns it to the Flag field.
func (o *AddressTx) SetFlag(v string) {
	o.Flag = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *AddressTx) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressTx) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *AddressTx) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *AddressTx) SetAddress(v string) {
	o.Address = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *AddressTx) GetTime() int64 {
	if o == nil || o.Time == nil {
		var ret int64
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressTx) GetTimeOk() (*int64, bool) {
	if o == nil || o.Time == nil {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *AddressTx) HasTime() bool {
	if o != nil && o.Time != nil {
		return true
	}

	return false
}

// SetTime gets a reference to the given int64 and assigns it to the Time field.
func (o *AddressTx) SetTime(v int64) {
	o.Time = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *AddressTx) GetHeight() int64 {
	if o == nil || o.Height == nil {
		var ret int64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressTx) GetHeightOk() (*int64, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *AddressTx) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int64 and assigns it to the Height field.
func (o *AddressTx) SetHeight(v int64) {
	o.Height = &v
}

// GetIncome returns the Income field value if set, zero value otherwise.
func (o *AddressTx) GetIncome() int64 {
	if o == nil || o.Income == nil {
		var ret int64
		return ret
	}
	return *o.Income
}

// GetIncomeOk returns a tuple with the Income field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressTx) GetIncomeOk() (*int64, bool) {
	if o == nil || o.Income == nil {
		return nil, false
	}
	return o.Income, true
}

// HasIncome returns a boolean if a field has been set.
func (o *AddressTx) HasIncome() bool {
	if o != nil && o.Income != nil {
		return true
	}

	return false
}

// SetIncome gets a reference to the given int64 and assigns it to the Income field.
func (o *AddressTx) SetIncome(v int64) {
	o.Income = &v
}

// GetOutcome returns the Outcome field value if set, zero value otherwise.
func (o *AddressTx) GetOutcome() int64 {
	if o == nil || o.Outcome == nil {
		var ret int64
		return ret
	}
	return *o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressTx) GetOutcomeOk() (*int64, bool) {
	if o == nil || o.Outcome == nil {
		return nil, false
	}
	return o.Outcome, true
}

// HasOutcome returns a boolean if a field has been set.
func (o *AddressTx) HasOutcome() bool {
	if o != nil && o.Outcome != nil {
		return true
	}

	return false
}

// SetOutcome gets a reference to the given int64 and assigns it to the Outcome field.
func (o *AddressTx) SetOutcome(v int64) {
	o.Outcome = &v
}

// GetTxid returns the Txid field value if set, zero value otherwise.
func (o *AddressTx) GetTxid() string {
	if o == nil || o.Txid == nil {
		var ret string
		return ret
	}
	return *o.Txid
}

// GetTxidOk returns a tuple with the Txid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressTx) GetTxidOk() (*string, bool) {
	if o == nil || o.Txid == nil {
		return nil, false
	}
	return o.Txid, true
}

// HasTxid returns a boolean if a field has been set.
func (o *AddressTx) HasTxid() bool {
	if o != nil && o.Txid != nil {
		return true
	}

	return false
}

// SetTxid gets a reference to the given string and assigns it to the Txid field.
func (o *AddressTx) SetTxid(v string) {
	o.Txid = &v
}

func (o AddressTx) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Flag != nil {
		toSerialize["flag"] = o.Flag
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Time != nil {
		toSerialize["time"] = o.Time
	}
	if o.Height != nil {
		toSerialize["height"] = o.Height
	}
	if o.Income != nil {
		toSerialize["income"] = o.Income
	}
	if o.Outcome != nil {
		toSerialize["outcome"] = o.Outcome
	}
	if o.Txid != nil {
		toSerialize["txid"] = o.Txid
	}
	return json.Marshal(toSerialize)
}

type NullableAddressTx struct {
	value *AddressTx
	isSet bool
}

func (v NullableAddressTx) Get() *AddressTx {
	return v.value
}

func (v *NullableAddressTx) Set(val *AddressTx) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressTx) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressTx) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressTx(val *AddressTx) *NullableAddressTx {
	return &NullableAddressTx{value: val, isSet: true}
}

func (v NullableAddressTx) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressTx) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
